### ISSUE TITLE
Reprappro link does nto work

### ISSUE THREAD

**Issue by joochung** [MechanizedMedic/gskewer#1]
The reprappro link doesn't work. Would you happen to have a copy of the documentation for calculating the required skew values?

**Comment by MechanizedMedic** [comment]
Oh no, it looks like RepRapPro went out of business! ... I'll work on some proper instructions as my schedule allows, but for now...
To measure the amount of error print/mill a cube with the sides of the cube being parallel to the axes of the machine (the larger, the better). The cube will be out of square just at the machine is. The error measurement is how far out of square the axis pairs are out from each other in millimeters. The skew.py executable will accept each length and error measurement individually or as a tangent angle for each axis pair. Here is a summary of available arguments:

> --xyerr [Error in the X-axis for the XY pair in mm.]
> --zxerr [Error in the Z-axis for the ZX pair in mm.]
> --yzerr [Error in the Y-axis for the YZ pair in mm.]
> 
> --xylen [Length of the side where the XY error measurement was taken. This is optional, default value is 100mm]
> --yzlen [Length of the side where the YZ error measurement was taken. This is optional, default value is 100mm]
> --zxlen [Length of the side where the ZX error measurement was taken. This is optional, default value is 100mm]
> 
> --xytan [The error in the XY pair as a tangent. (xyerr/xylen)]
> --yztan [The error in the YZ pair as a tangent. (yzerr/yzlen)]
> --zxtan [The error in the ZX pair as a tangent. (zxerr/zxlen)]

You also have the option of editing these values in the script itself once you get your numbers dialed in.

**Comment by MechanizedMedic** [comment]
[Here are the original instructions.](http://www.zs1jen.org/Station_Manuals/Reference/3D_Printers/14_RepRapPro_-_Axis_compensation.pdf) The files you'll need to print [are here](https://github.com/reprappro/RepRapFirmware/blob/master/STL/calibration_90mm.stl).

**Comment by MechanizedMedic** [comment]
Thank you for reporting this btw, I updated the readme with the links above. Closing this issue.

**Comment by nyxaria** [comment]
@MechanizedMedic do you mind re-uploading the PDFs please?

**Comment by MechanizedMedic** [comment]
@nyxaria the links are shared above. If those links are dead then... whoopsies!
